# Generated by Django 5.0.7 on 2024-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
