# Generated by Django 5.0.7 on 2024-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpost_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
